### ISSUE TITLE
ID3 Tags ? iptc umbennen in meadiameta oder so ;)

### ISSUE THREAD

**Issue by dergel** [olien/iptc#5]
Hi,

vielleicht das Ganze erweitern um allgemeine Metadaten in Medien. D.h. z.b. bei mp3 die ID3 Tags ... Das wäre fein, aehh sorry - geschmeidig :)

@olien ja, jetzt bekommst du hier issues über issues .. Hau rein Oli :)

**Comment by olien** [comment]
OK. Danke. Immer weiter so!

**Comment by jdlx** [comment]
`media_meta` o.ä. als Addonname wäre sicherlich sinnvoll.. erstmal flach halten würde ich den Ball allerdings mit non-image Metadaten.. allein Bildmetadaten sind schon ein riesen Feld mit genung Fallstricken.. Stichwort XMP usw. Auch würde ich das Thema von vornherein auf rein lesenden Zugriff beschränken (der editier Wunsch wird 100% mal kommen.. Finger weg sach ich ma ;)

**Comment by dergel** [comment]
Editieren fände ich auch nicht sinnvoll, für dieses AddOn.. Aber das um allgemeine Daten zu ergänzen schon.. Aber ist ja nicht mein AddOn .. Kann der Oli ja machen wie er will..

**Comment by olien** [comment]
Addon wird nicht mehr weiter entwickelt…
