### ISSUE TITLE
[linklist] Libs & sonstiges resources rund ums Thema..

### ISSUE THREAD

**Issue by jdlx** [olien/iptc#6]
Ein Anfang.. aus meinem Recherche Archiv..
- https://github.com/lsolesen/pel (lange Zeit das modernste auf dem Markt, aber aktuell auch nicht mehr aktiv weiterentwickelt..)
- http://www.ozhiker.com/electronics/pjmt/index.html (mauer/alter Code, aber afaik umfassendste Makernotes Unterstützung..)
- http://www.exiv2.org/sample.html
- http://xmpphptoolkit.sourceforge.net/

**Comment by olien** [comment]
danke sehr

**Comment by olien** [comment]
Addon wird nicht mehr weiter entwickelt…
